name: Publish package to GitHub Packages
on:
  push:
      tags:
      - 'v*'
jobs:
  publish:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_ACTOR: ${{ secrets.GH_ACTOR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract Version
        id: extract_version
        run: |
          VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"
      - name: Set Version as Env Variable
        run: echo "VERSION=${{ steps.extract_version.outputs.version }}" >> $GITHUB_ENV
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Publish package
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
